### ISSUE TITLE
Does the model working?

### ISSUE THREAD

**Issue by seeb0h** [mvrl/GeoSynth#4]
Hi ! This looks super nice but I can't succeed to use it.

I download `https://huggingface.co/MVRL/GeoSynth/blob/main/sd-base-geosynth.ckpt`

Impossible to load it with A1111:
```
changing setting sd_model_checkpoint to geosynth_sd_loc-v3.ckpt [6223d68433]: AttributeError
Traceback (most recent call last):
  File "/Users/tmp/code/stable-diffusion-webui/modules/options.py", line 165, in set
    option.onchange()
  File "/Users/tmp/code/stable-diffusion-webui/modules/call_queue.py", line 13, in f
    res = func(*args, **kwargs)
  File "/Users/tmp/code/stable-diffusion-webui/modules/initialize_util.py", line 181, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: sd_models.reload_model_weights()), call=False)
  File "/Users/tmp/code/stable-diffusion-webui/modules/sd_models.py", line 869, in reload_model_weights
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "/Users/tmp/code/stable-diffusion-webui/modules/sd_models.py", line 330, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "/Users/tmp/code/stable-diffusion-webui/modules/sd_models.py", line 314, in read_state_dict
    sd = get_state_dict_from_checkpoint(pl_sd)
  File "/Users/tmp/code/stable-diffusion-webui/modules/sd_models.py", line 253, in get_state_dict_from_checkpoint
    pl_sd = pl_sd.pop("state_dict", pl_sd)
AttributeError: 'NoneType' object has no attribute 'pop'
```

So I convert it first in `.safetensors`. And it succeeds to load it.

Then I try a very simple text2image test with only this prompt `Satellite image features a city neighborhood` and default parameters.
I get this kind of error
```
      File "/Users/famille/Documents/_Seb/Bidouilles/code/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
        return F.linear(input, self.weight, self.bias)
    RuntimeError: linear(): input and weight.T shapes cannot be multiplied (77x1024 and 768x320)
```

**Comment by Vishu26** [comment]
Hi! I am not sure how you are trying to load the model. But this model should be easy to load using `diffusers`. Below is the code snippet:

```
from diffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained("MVRL/GeoSynth")
pipe = pipe.to("cuda:0")
```

**Comment by seeb0h** [comment]
I download again the .ckpt and now it is working (great!)
Sorry for the unnecessary issue
